version: '3'
services:

  php:
    container_name: l2php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 54433:8000
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    container_name: l2mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=AsQw!2AsQw!2
      - MYSQL_DATABASE=users
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=AsQw!2AsQw!2
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3309:3306

  phpmyadmin:
    container_name: l2pma
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=AsQw!2AsQw!2

  rabbitmq:
    container_name: l2rmq
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  mysql_data:
